// //AUTH
// export const GET_USER = "GET_USER";
// export const REMOVE_USER = "REMOVE_USER";

//RESTAURANTS
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const CURRENT_RESTAURANT = 'CURRENT_RESTAURANT';


